---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: registry.redhat.io/ansible-automation-platform-22/ee-minimal-rhel8:1.0.0-128

dependencies:
  galaxy: requirements.yml

additional_build_steps:
  append:
    - COPY app /runner
